FORMAT: 1A
HOST: https://www.onlinescoutmanager.co.uk/

# Online Scout Manager

I'm documenting the Online Scout Manager API here as I discover it,
you can contribute by forking it on GitHub.

## Authorisation [/users.php?action=authorise]

### Authorise [POST /users.php?action=authorise&email={email}&password={password}&token={token}&apiid={apiid}]

    Note you need email and password the first time to authorise your application against your account, 
    after that you can use the usertoken.

+ Parameters

    + token (string, required) - your OSM API token
    + apiid (string, required) - your OSM API ID
    + email (string, optional) - your OSM login email address
    + password (string, optional) - your OSM login password
    


+ Response 200 (application/json)
demo